# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8e3bd2f25069cc2942e42474045c35478b0317d1a840143aa08fe684aa29b7d9a8d2b78edebef59e7697703029817c45ef1e487f6565091fa909d7db6ed247a

test:
  secret_key_base: cd20639467a8a110c32524cbc87360878aabdb03d0086108cd823543eeef58283c785eb9bd629499019eff73beb9664546fd876633211259a94a194f408f9e67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
